# Generated by Django 3.1.7 on 2021-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cats_number',
            field=models.IntegerField(default=0),
        ),
    ]
